name:                typson-beam
version:             0.1.0.0
github:              "aaronallen8455/typson"
license:             BSD3
author:              "Aaron Allen"
maintainer:          "aaronallen8455@gmail.com"
copyright:           "2020 Aaron Allen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aaronallen8455/typson#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- beam-core >= 0.9.0.0 && < 0.10.0.0
- beam-postgres >= 0.5.0.0 && < 0.6.0.0
- postgresql-simple
- typson-core

library:
  source-dirs: src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror=missing-fields
    - -Werror=incomplete-patterns

    dependencies:
    - HUnit
    - aeson
    - beam-core
    - beam-migrate
    - beam-postgres
    - bytestring
    - exceptions
    - hedgehog
    - microlens
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - typson-beam
    - test-fixture
    - postgresql-simple
