name:                typson-selda
version:             0.1.0.0
github:              "aaronallen8455/typson"
license:             BSD3
author:              "Aaron Allen"
maintainer:          "aaronallen8455@gmail.com"
copyright:           "2020 Aaron Allen"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Typson Selda Integration
category: Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aaronallen8455/typson#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- typson-core
- selda
- selda-postgresql
- selda-json
- text
- aeson

library:
  source-dirs: src

tests:
  typson-selda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - aeson
    - bytestring
    - exceptions
    - hedgehog
    - microlens
    - selda
    - selda-json
    - selda-postgresql
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - test-fixture
    - test-fixture
    - typson-selda
